[package]
name = "voxeldefense"
version = "0.1.0"
authors = ["Elijah Seed Arita <bananatrooper52@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22"
ash = "*"